Nikhil Joshi
Btech EXTC VIII sem
C020

In [50]:
#Q1)
string1="Hello World"
print(string1[-1:]+string1[1:-1]+string1[:1])



dello WorlH


In [16]:
# Q2)
num1=int(input("ENter a number"))
rem=0
list1=[]
while (num1>0):
  rem=num1%10
  num1=int(num1/10)

  list1.append(rem)
print(list1)

def convert(list): 
      
    # Converting integer list to string list 
    s = [str(i) for i in list] 
      
    # Join list items using join() 
    res = int("".join(s)) 
      
    return(res)
print(convert(list1))
  

ENter a number1234
[4, 3, 2, 1]
4321


In [19]:
#Q3)

list1=[123,65,7890,5642,65,45,43,45,51]
sorted_list=list1.sort()
print('second minimun= ',list1[1])
print('second maximum= ',list1[-2])

second minimun=  45
second maximum=  5642


In [21]:
# Q4)
list1=[45,65,78,90,34,12,444,6565,78885,3421]
list2=[]
for item in list1:
  if(item%5!=0):
    list2.append(item)
print(list2)


[78, 34, 12, 444, 3421]


In [32]:
# Q5a,b
import numpy as np
arr1=np.random.rand(4,4)
print(arr1)
arr2=arr1[2:3]
print("The elements of the third row = ", arr2)

[[0.62694166 0.16136701 0.76881278 0.34071043]
 [0.95147142 0.95621903 0.18258448 0.52701522]
 [0.35865233 0.55477807 0.77259693 0.92653835]
 [0.04365126 0.61662094 0.1278712  0.09305506]]
The elements of the third row =  [[0.35865233 0.55477807 0.77259693 0.92653835]]


In [33]:
# Q5c)

print(arr1.reshape(2,8))

[[0.62694166 0.16136701 0.76881278 0.34071043 0.95147142 0.95621903
  0.18258448 0.52701522]
 [0.35865233 0.55477807 0.77259693 0.92653835 0.04365126 0.61662094
  0.1278712  0.09305506]]


In [49]:
# Q6)
def add_int(a,b):
  return int(a+b)
print (add_int(3,9))

12


In [41]:
#Q7)

dict1={
    "name":"Nikhil Joshi",
    "Age":21,
    "phone_no":"09430984093"
}


In [51]:
#Q8)

print(dict1.keys())
for k,v in dict1.items():
  print(v)

dict_keys(['name', 'Age', 'phone_no'])
Nikhil Joshi
21
09430984093
